### ISSUE TITLE
Path to release

### ISSUE THREAD

**Issue by scott-fleischman** [freebroccolo/vscode-agda#13]
What things are left to bring this extension to a usable release?

I am giving a workshop on an introduction to Agda in January and I'm curious if I could recommend using this extension. I'm a bit concerned with the comments in the readme, and I wonder if long-term a different approach would be best (such as some kind of new Agda language server).

I have some time between now and then that I could devote to working on the extension, although I don't have any experience with VS Code extension development.

**Comment by freebroccolo** [comment]
Good question.

I think the current plugin architecture is viable but it does need a bit of work to get to where I would consider it a real alternative to the emacs mode.

It can be used now though and syntax highlighting does work with the caveats noted in the README. One possible way to just eliminate the problem is to automatically save the document on visibility change. I don't really like that behavior for a number of reasons but it might not be that bad of an option until a proper solution can be implemented.

Trying to develop a new server architecture on the agda side would be ideal but I think that will be a ton of work and unless upstream is interested in doing that it would also be very hard to maintain.

As far as current communication with the server goes, most of the foundation is in place to start building up all of the interactive features. What needs to happen to support those is the [parser](https://github.com/freebroccolo/vscode-agda/blob/master/src/shared/agda/sexp/parser.ts) needs to handle goal related commands and then the client needs to be able to tell the server to produce the various commands to change the agda interaction state. Most of the commands can be found [here](https://github.com/agda/agda/blob/master/src/full/Agda/Interaction/InteractionTop.hs#L328) and then you can see how they are dealt with in the [emacs mode](https://github.com/agda/agda/blob/master/src/data/emacs-mode/agda2-mode.el).

So I think it is possible to get something usable by January. It may not be quite at feature parity with the emacs mode but most of the important stuff could be in place by then.

If you want to try using or working on the extension, I believe there may be a bug in the current implementation that results in incorrect highlighting being applied when multiple files are refreshed in certain circumstances. I think I know what is causing it and how to fix it but I haven't gotten to it yet. But if that happens you can just do an edit and save or something and it should resolve itself.

**Comment by freebroccolo** [comment]
By the way, if you want to try to use the current plugin, you can just clone the repo, open the directory in vscode, and hit F5. This will load a new window as the extension host with the agda plugin loaded. Then you can open agda files in that window and try it out.

There are some docs on how to get started writing an extension [here](https://code.visualstudio.com/Docs/extensions/example-hello-world) and these also cover the extension layout and related details.

The vscode API is [here](https://code.visualstudio.com/Docs/extensionAPI/vscode-api). As far as the language server API is concerned, you can find it in the github repos but what I usually do is just check out what's available by using the intellisense and code peak functionality. For example, if you want to know what a type is for in the language server API, you can do a cmd+click to jump to its declaration.

**Comment by freebroccolo** [comment]
The basic architecture for extensions is that there is an `activate` function that the plugin implements and this is the entry point from the editor's perspective. During `activate` you will usually do things like set up the initial state and register callbacks to various editor events like opening or saving files.

The language server API exposes several event hooks through `connection`, and you can see how that works in the full featured case [here](https://github.com/freebroccolo/ocaml-language-server/blob/master/src/server/index.ts).

To initiate commands from the editor side (which could go on to talk to the server), you can register commands with the editor like [here](https://github.com/freebroccolo/vscode-reasonml/blob/master/src/client/command/doSplitCases.ts#L53). These commands are associated with some textual key, and that key can be used in the keybinding settings and some other places.

**Comment by scott-fleischman** [comment]
Thanks for the helpful comments. I've got it working locally (dracula is not the best theme I noticed!). I'll poke around a bit to get a sense of how things are working.

**Comment by scott-fleischman** [comment]
Also I had do an `npm install` in the cloned directory to get the extension to work. It's a pretty obvious thing to do but easy to miss.

**Comment by freebroccolo** [comment]
Yeah, the theme I am currently using with this extension is `Quiet Light`.

The problem with the way agda does highlighting is that it's independent of the theme. I think we might be able to try and build a palette dynamically based on the current editor theme but it's a bit tricky and I'm not even sure if it's possible directly through the API yet. But it would be at least a little bit better if we defined a separate palette for light and dark themes and that is already supported to some extent in the API.

**Comment by freebroccolo** [comment]
One other thing I forgot to mention. You can symlink the extension repo into `~/.vscode/extensions/vscode-agda` if you want to install and run it normally outside of the extension host.

**Comment by scott-fleischman** [comment]
FYI—It looks like I overestimated the time I will have this month and underestimated the time to prepare for my workshop. I don't expect to be able to look at this project more deeply until January. It's still a project I would like to see to completion, though. And I'm also interested in trying to make heads or tails of Yggdrasil. I'll revisit my priorities in a month.

**Comment by freebroccolo** [comment]
No problem and thanks for the interest. I do intend to eventually get it into a usable state but it may take awhile with everything else on my plate at the moment. But I'm hoping to be able to do some more work on this in the next couple weeks.
