### ISSUE TITLE
Approximate vs Accurate highlighting

### ISSUE THREAD

**Issue by bd82** [freebroccolo/vscode-agda#14]
Hello.

Just a declaimer: I'm not familiar with Agda, but I am familiar with syntax highlighting
and the Parsing Library (Chevrotain) you have used (I'm the main author).

I am trying to understand the reason why there are two highlighting modes?
Does highlighting Agda source code requires semantic information and not just 
the result of the lexer?

**Comment by freebroccolo** [comment]
Hi @bd82!

Yes, agda has a very flexible and somewhat unusual syntax due to the use of mixfix operators. This lets you implement certain things like conditionals as operators:

```
if_then_else_ : {A : Set} → Bool → A → A → A
if true then x else y = x
if false then x else y = y
```

Unfortunately, because operators can be prefix, postfix, or mixfix-infix like this, there is no easy way to do accurate parsing from an external tool. In order to do accurate parsing externally, you would need to be able to process all of the modules the current file depends upon, in addition to supporting dynamic rule updates (as new operators are encountered, etc.).

So the way this plugin currently works is it tries to do a reasonable job just with the lexer and then requests the accurate highlighting information from the server after the file is loaded into the interpreter.

Below is an example of what a typical file might look like when accurately highlighted. As you can see, it would be hard to detect which tokens are meant as pieces of data and which are meant as functions just through the lexer.

![agda](https://cloud.githubusercontent.com/assets/151197/20818171/38ab16cc-b7e9-11e6-9621-20799ca4fddb.png)

**Comment by bd82** [comment]
Thanks for the explanation.

This effectively means that agda syntax is defined "on the fly".
Which will probably require a much more interpreted (and slower) approach to support in a parser.
Or alternatively requires defining a "super set" grammar which accepts everything that seems even remotely valid and figure the actual meaning at a later stage.

The Parser you have implemented here:
https://github.com/freebroccolo/vscode-agda/tree/master/src/shared/agda/sexp
Is it just for some type of agda annotations? or for agda in general?

**Comment by freebroccolo** [comment]
@bd82 yes, that's correct. There is a paper [here](http://www.cse.chalmers.se/~nad/publications/danielsson-norell-mixfix.pdf) that describes one algorithm for handling this style of parsing.

As for the parser in that file you linked to, it is for the s-expression responses that are received from the `agda --interaction` process. This process loads a kind of REPL that the editor is meant to send commands to and then the REPL responds with results from the type checker or from the evaluator or some other part of the system.

Originally the system was built specifically for emacs, so those commands would just be run directly with elisp `eval` but here we need to do something more than that.

**Comment by bd82** [comment]
Thank you @freebroccolo. I will examine that paper, perhaps it will provide some ideas
for more dynamic capabilities in Chevrotain, But because Chevrotain Parsers are not interpreted there is a limit to what can be reasonably achieved in terms of dynamic capabilities.

Now I understand that this project **integrates** existing language services (agda --interaction) into VSCode. At first I thought it both implements the language services and integrates them into VSCode.
