### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by chantisnake** [freebroccolo/vscode-agda#18]
I see there was no update since May last year.

**Comment by freebroccolo** [comment]
Not currently. At the time I began implementing this there were a number of issues with how the interaction with the agda interpreter worked which made it not a great fit for the language server model.

There is a recent effort to provide a different interaction mode. I think it is based on the LSP but I haven't looked at it in detail. At some point I might try to implement that but it probably won't be for awhile because I don't have much free time to work on the project these days.
